# Generated by Django 5.2 on 2025-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', '超級管理員'), ('owner', '公司老闆'), ('admin', '公司管理員'), ('experimenter', '實驗者')], default='admin', max_length=20),
        ),
    ]
