# Generated by Django 5.2 on 2025-04-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_login_code_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司', 'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用戶', 'verbose_name_plural': '用戶'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真實姓名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='公司代碼'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company', verbose_name='所屬公司'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='登入代碼'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', '超級管理員'), ('owner', '公司老闆'), ('admin', '公司管理員'), ('experimenter', '實驗者')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
