# Generated by Django 5.2 on 2025-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='登入帳號'),
        ),
    ]
