# Generated by Django 5.1.6 on 2025-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_experiment_data'),
    ]

    operations = [
        # 只保留添加欄位的操作，移除唯一約束的操作
        migrations.AddField(
            model_name='formsubmission',
            name='time_segment',
            field=models.IntegerField(default=1),
        ),
        # 移除下面的唯一約束操作
        # migrations.AlterUniqueTogether(
        #     name='formsubmission',
        #     unique_together={('worker', 'form_type', 'submission_count', 'time_segment')},
        # ),
    ]