# Generated by Django 5.1.6 on 2025-05-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_duplicate_submissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formsubmission',
            unique_together=set(),
        ),
    ]
