# Generated by Django 5.1.6 on 2025-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_formsubmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
