# Generated by Django 5.1.6 on 2025-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_formsubmission_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', '超級管理員'), ('owner', '公司老闆'), ('admin', '公司管理員'), ('experimenter', '實驗者'), ('super_experimenter', '超級實驗者')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
