# Generated by Django 5.1.6 on 2025-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_super_company',
            field=models.BooleanField(default=False, verbose_name='是否為超級實驗公司'),
        ),
    ]
