# Generated by Django 5.1.6 on 2025-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_is_super_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_super_experimenter',
            field=models.BooleanField(default=False, verbose_name='是否為超級實驗者'),
        ),
    ]
