# Generated by Django 5.1.6 on 2025-05-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_is_super_experimenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_super_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_super_experimenter',
        ),
    ]
